//import { useState } from 'react';
import React, { Component } from "react";
import Head from "next/head";
import styles from "./index.module.scss";
import { observer } from "mobx-react";
import store from "./store";
@observer
class Counter extends Component {
  //const [count, setCount] = useState(0);
  render() {
    return (
      <div className={styles.counter}>
        <div className={styles.button} onClick={() => store.decrement()}>
          -
        </div>
        <div className={styles.count}>{store.counter}</div>
        <div className={styles.button} onClick={() => store.increment()}>
          +
        </div>
        <div
          className={`${styles.button} ${styles.resetButton}`}
          onClick={() => store.reset()}
        >
          Reset
        </div>
      </div>
    );
  }
}

class Home extends Component {
  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Counter />
      </div>
    );
  }
}

export default Home;
